# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create([
    {username: "chrispolanco", email: "chrispolanco@sbcglobal.net", first_name: "Christian", last_name: "Polanco", password: "password"}, 
    {username: "joss", email: "joss@gmail.net", first_name: "Joss", last_name: "Fuentes", password: "password"},
    {username: "dempsey", email: "dempsey@gmail.net", first_name: "Dempsey", last_name: "Polanco", password: "password"},
    {username: "chocolate", email: "chocolate@gmail.net", first_name: "Chocolate", last_name: "Fuentes", password: "password"},
    {username: "bella", email: "bella@gmail.net", first_name: "Bella", last_name: "Polanco", password: "password"}
]); 

Post.create([
    {story: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", votes:10, location: "Los Angeles, CA", user_id: 1},
    {story: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.", votes:10, location: "Los Angeles, CA", user_id: 1}, 
    {story: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).", votes:9, location: "Boulder, CO", user_id: 2}, 
    {story: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).", votes:9, location: "Boulder, CO", user_id: 2}, 
    {story: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, comes from a line in section 1.10.32.The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.", votes:8, location: "Portland, OR", user_id: 3}, 
    {story: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.", votes:8, location: "Austin, TX", user_id: 4}, 
    {story: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", votes:7, location: "San Diego, CA", user_id: 5}
]); 

Comment.create([
    {context: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dictum non consectetur a erat nam. Vel pharetra vel turpis nunc eget lorem dolor. Vitae justo eget magna fermentum iaculis. Quis risus sed vulputate odio ut enim blandit volutpat maecenas. Elit ullamcorper dignissim cras tincidunt lobortis feugiat. Egestas tellus rutrum tellus pellentesque eu. Lacus viverra vitae congue eu consequat ac felis donec et. Feugiat nisl pretium fusce id velit ut tortor pretium viverra. Mi ipsum faucibus vitae aliquet. Sagittis eu volutpat odio facilisis mauris sit amet massa. At erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Duis ut diam quam nulla. Dui faucibus in ornare quam viverra orci sagittis eu. Sem viverra aliquet eget sit. Felis bibendum ut tristique et egestas quis ipsum suspendisse.", user_id: 1, post_id: 1}, 
    {context: "Tristique magna sit amet purus gravida quis blandit. Eros in cursus turpis massa tincidunt dui ut. Risus viverra adipiscing at in tellus integer feugiat scelerisque. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Id semper risus in hendrerit gravida rutrum quisque non tellus. Aliquam faucibus purus in massa tempor nec. Quisque egestas diam in arcu cursus euismod quis viverra. Proin fermentum leo vel orci porta non pulvinar neque. Congue quisque egestas diam in arcu cursus. Arcu dui vivamus arcu felis bibendum ut tristique et egestas. Amet consectetur adipiscing elit pellentesque. At tempor commodo ullamcorper a. Dolor sit amet consectetur adipiscing elit duis tristique. Sed odio morbi quis commodo odio. Quis eleifend quam adipiscing vitae proin.", user_id: 2, post_id: 2}, 
    {context: "Pretium lectus quam id leo in vitae turpis massa. In ornare quam viverra orci sagittis eu. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. Nibh tellus molestie nunc non blandit massa enim. Porta lorem mollis aliquam ut porttitor. Sapien nec sagittis aliquam malesuada bibendum. Aenean sed adipiscing diam donec adipiscing tristique risus nec. Enim praesent elementum facilisis leo vel. Scelerisque felis imperdiet proin fermentum leo vel orci porta non. Risus commodo viverra maecenas accumsan. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare. Orci a scelerisque purus semper eget duis. Tempus urna et pharetra pharetra. Feugiat vivamus at augue eget arcu. Varius morbi enim nunc faucibus a. Urna molestie at elementum eu facilisis. Etiam tempor orci eu lobortis elementum nibh. Elit at imperdiet dui accumsan. Sed felis eget velit aliquet. In ornare quam viverra orci.", user_id: 3, post_id: 3},
    {context: "Sollicitudin tempor id eu nisl nunc mi. Donec ultrices tincidunt arcu non sodales neque sodales ut. Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Tempor commodo ullamcorper a lacus vestibulum. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Aliquet nec ullamcorper sit amet risus nullam. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. A arcu cursus vitae congue mauris rhoncus aenean. Proin sed libero enim sed faucibus turpis. Ac feugiat sed lectus vestibulum mattis. Tristique senectus et netus et malesuada fames. Sed risus pretium quam vulputate. Elementum curabitur vitae nunc sed velit. Fermentum dui faucibus in ornare quam viverra.", user_id: 4, post_id: 4}, 
    {context: "Sollicitudin tempor id eu nisl nunc mi. Donec ultrices tincidunt arcu non sodales neque sodales ut. Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Tempor commodo ullamcorper a lacus vestibulum. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Aliquet nec ullamcorper sit amet risus nullam. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. A arcu cursus vitae congue mauris rhoncus aenean. Proin sed libero enim sed faucibus turpis. Ac feugiat sed lectus vestibulum mattis. Tristique senectus et netus et malesuada fames. Sed risus pretium quam vulputate. Elementum curabitur vitae nunc sed velit. Fermentum dui faucibus in ornare quam viverra.", user_id: 4, post_id: 4}, 
    {context: "Sollicitudin tempor id eu nisl nunc mi. Donec ultrices tincidunt arcu non sodales neque sodales ut. Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Tempor commodo ullamcorper a lacus vestibulum. Ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Aliquet nec ullamcorper sit amet risus nullam. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat. A arcu cursus vitae congue mauris rhoncus aenean. Proin sed libero enim sed faucibus turpis. Ac feugiat sed lectus vestibulum mattis. Tristique senectus et netus et malesuada fames. Sed risus pretium quam vulputate. Elementum curabitur vitae nunc sed velit. Fermentum dui faucibus in ornare quam viverra.", user_id: 4, post_id: 4}, 
    {context: "Sagittis purus sit amet volutpat consequat mauris. Arcu non odio euismod lacinia at quis risus sed. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Nisl tincidunt eget nullam non nisi. Pellentesque elit eget gravida cum sociis natoque penatibus et. Consectetur purus ut faucibus pulvinar elementum integer enim. Porta lorem mollis aliquam ut porttitor leo a. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Sed adipiscing diam donec adipiscing tristique. Purus in mollis nunc sed.Quam id leo in vitae turpis massa sed elementum. Tristique risus nec feugiat in fermentum posuere urna. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. Id cursus metus aliquam eleifend mi in nulla posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada. Tellus molestie nunc non blandit massa enim. Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Eu lobortis elementum nibh tellus molestie nunc non blandit. Sit amet volutpat consequat mauris nunc congue nisi vitae. Et netus et malesuada fames ac turpis egestas. Tristique sollicitudin nibh sit amet. Sit amet tellus cras adipiscing enim eu turpis. Nisl pretium fusce id velit ut tortor pretium viverra. Sit amet porttitor eget dolor morbi non. Blandit aliquam etiam erat velit scelerisque. Risus viverra adipiscing at in tellus integer feugiat. Orci porta non pulvinar neque laoreet suspendisse interdum. Sollicitudin tempor id eu nisl nunc.", user_id: 5, post_id: 5},
    {context: "Sagittis purus sit amet volutpat consequat mauris. Arcu non odio euismod lacinia at quis risus sed. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus ornare. Nisl tincidunt eget nullam non nisi. Pellentesque elit eget gravida cum sociis natoque penatibus et. Consectetur purus ut faucibus pulvinar elementum integer enim. Porta lorem mollis aliquam ut porttitor leo a. Vel fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Tellus in hac habitasse platea dictumst vestibulum rhoncus est. Sed adipiscing diam donec adipiscing tristique. Purus in mollis nunc sed.Quam id leo in vitae turpis massa sed elementum. Tristique risus nec feugiat in fermentum posuere urna. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. Id cursus metus aliquam eleifend mi in nulla posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada. Tellus molestie nunc non blandit massa enim. Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Eu lobortis elementum nibh tellus molestie nunc non blandit. Sit amet volutpat consequat mauris nunc congue nisi vitae. Et netus et malesuada fames ac turpis egestas. Tristique sollicitudin nibh sit amet. Sit amet tellus cras adipiscing enim eu turpis. Nisl pretium fusce id velit ut tortor pretium viverra. Sit amet porttitor eget dolor morbi non. Blandit aliquam etiam erat velit scelerisque. Risus viverra adipiscing at in tellus integer feugiat. Orci porta non pulvinar neque laoreet suspendisse interdum. Sollicitudin tempor id eu nisl nunc.", user_id: 5, post_id: 5}
]);  